# Generated by Django 3.1.2 on 2020-10-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='language',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='module',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
